### ISSUE TITLE
Python error when selecting an object

### ISSUE THREAD

**Issue by martinsluka** [desertwolf7/NumericalDigitize#4]
QGIS version | 3.20.2-Odense | QGIS code revision | 9f59a15664
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.8.7
GDAL/OGR version | 3.2.3
PROJ version | 6.3.2
EPSG Registry database version | v9.8.6 (2020-01-22)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
PDAL version | 2.2.0
PostgreSQL client version | 12.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.4
OS version | macOS High Sierra (10.13)
  |   |   |  
Active Python plugins | 
db_manager
MetaSearch
processing
numericalDigitize
latlontools
quick_map_services
SemiAutomaticClassificationPlugin
valuetool

ERROR :

2021-09-01T19:45:12     WARNING    Traceback (most recent call last):
              File "/Users/studiosluka_3/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/numericalDigitize/numericalDigitize.py", line 264, in EditFeature
              self.__dlgEdit.setValues(coords)
              File "/Users/studiosluka_3/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/numericalDigitize/addFeatureGUI.py", line 263, in setValues
              model.setData(model.createIndex(i, 0), QVariant(self.coords_matrix[i][0]))
             RuntimeError: no access to protected functions or signals for objects not created from Python

**Comment by Northward-Design** [comment]
@desertwolf7 Same issue when editing:

2022-04-19T15:02:57     WARNING    Traceback (most recent call last):
              File "/home/ivan/.local/share/QGIS/QGIS3/profiles/default/python/plugins/numericalDigitize/numericalDigitize.py", line 264, in EditFeature
              self.__dlgEdit.setValues(coords)
              File "/home/ivan/.local/share/QGIS/QGIS3/profiles/default/python/plugins/numericalDigitize/addFeatureGUI.py", line 263, in setValues
              model.setData(model.createIndex(i, 0), QVariant(self.coords_matrix[i][0]))
             RuntimeError: no access to protected functions or signals for objects not created from Python

And When selecting 'Part No' when adding a new line:

2022-04-19T15:04:16     WARNING    Traceback (most recent call last):
              File "/home/ivan/.local/share/QGIS/QGIS3/profiles/default/python/plugins/numericalDigitize/addFeatureGUI.py", line 686, in partChanged
              self.refreshTable(currentRow)
              File "/home/ivan/.local/share/QGIS/QGIS3/profiles/default/python/plugins/numericalDigitize/addFeatureGUI.py", line 675, in refreshTable
              model.dataChanged.emit(model.createIndex(0, 0),
             RuntimeError: no access to protected functions or signals for objects not created from Python

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>


QGIS version | 3.20.0-Odense | QGIS code revision | decaadbb31
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.5
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.2 LTS
  |   |   |  
Active Python plugins 
numericalDigitize
geoscience
joinmultiplelines
quick_map_services
slyr_community
raster_tracer
Qgis2threejs
db_manager
processing
MetaSearch
</body></html>
