### ISSUE TITLE
setColumnWidth GUI bug

### ISSUE THREAD

**Issue by io-qar** [desertwolf7/NumericalDigitize#6]
I don't know if the author still maintain this QGIS plugin, but I occured on well-known bug which crushes the plugin and doesn't let a user to use it.

`2023-03-25T14:42:28     WARNING    Traceback (most recent call last):
  File "/home/jasonowsley/.local/share/QGIS/QGIS3/profiles/default/python/plugins/numericalDigitize/numericalDigitize.py", line 194, in run
  self.__dlg.configureDialog(self.__layergeometryType, self.__layerwkbType, self.__isMultiType,
  File "/home/jasonowsley/.local/share/QGIS/QGIS3/profiles/default/python/plugins/numericalDigitize/addFeatureGUI.py", line 210, in configureDialog
  self.twPoints.setColumnWidth(i, self.twPoints.width()/self.twPoints.columnCount())
 TypeError: setColumnWidth(self, int, int): argument 2 has unexpected type 'float'
`
Moreover, the solution for this is quiet [simple](https://gis.stackexchange.com/a/456164).

**Comment by io-qar** [comment]
This issue was closed by @desertwolf7 in the [0.4.8 release](https://plugins.qgis.org/plugins/numericalDigitize/version/0.4.8/).
